# Generated by Django 5.2.3 on 2025-06-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_biblioteca.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_biblioteca.libro')),
            ],
        ),
    ]
